# Generated by Django 3.2.4 on 2021-06-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('dfrom', models.DateField()),
                ('dto', models.DateField()),
                ('discription', models.TextField(max_length=3000)),
                ('photo', models.ImageField(upload_to='project/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_location', to='Projects.location')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectimages/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_image', to='Projects.project')),
            ],
        ),
    ]
