# Generated by Django 3.2.4 on 2021-06-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='Cooperate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dfrom',
        ),
        migrations.RemoveField(
            model_name='project',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dto',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='cooperate',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='project_cooperate', to='Projects.cooperate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='Projects.type'),
            preserve_default=False,
        ),
    ]
