# Generated by Django 3.2.4 on 2021-06-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20210626_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cooperate',
        ),
        migrations.AddField(
            model_name='project',
            name='cooperate',
            field=models.ManyToManyField(to='Projects.Cooperate'),
        ),
    ]
